### ISSUE TITLE
db hints

### ISSUE THREAD

**Issue by vitaly-t** [jurvis/columbus#1]
instead of using this:

``` js
db.one("INSERT INTO Users(email, firstname, lastname) values($1, $2, $3) returning id", [requestBody.email, requestBody.firstname, requestBody.lastname])
```

you can use this:

``` js
db.one("INSERT INTO Users(email, firstname, lastname) values(${email}, ${firstname}, ${lastname}) returning id", requestBody)
```

And instead of using this:

``` js
db.none("INSERT INTO Records(user_id, imageurl, audiourl, daterecorded, location) values($1, $2, $3, $4, 'POINT($5 $6)')",
    [requestBody.account_id, requestBody.image_url, requestBody.audio_url, requestBody.timestamp, requestBody.location.lat, requestBody.location.lon])
```

you can use this:

``` js
providesLocation(requestBody);
db.none("INSERT INTO Records(user_id, imageurl, audiourl, daterecorded, location) values(${account_id}, ${image_url}, ${audio_url}, ${timestamp}, ${getLocation})", requestBody);
```

with the help of the powerful [Custom Type Formatting](https://github.com/vitaly-t/pg-promise#custom-type-formatting):

``` js
function providesLocation(obj) {
    obj.getLocation = {
        formatDBType: function () {
            return pgp.as.format("POINT(${lat}, ${lon})", obj.location);
        }
    };
}
```

**Comment by jurvis** [comment]
sweet, this looks a lot better. thanks for the awesome library and taking the time to leave hints! :smile:

**Comment by vitaly-t** [comment]
This one:

``` js
db.one("SELECT * FROM users WHERE email='$1^'", email)
```

will do the same what the default variable formatting would:

``` js
db.one("SELECT * FROM users WHERE email=$1", email)
```

only safer.

**Comment by jurvis** [comment]
cool, thanks! no idea why I did that.

I'm facing some issues with the custom type formatting suggestion you gave: 
`return pgp.as.format("Point(${lon} ${lat})", obj.location);`

this outputs to `'Point(103.7716803 1.3104337)'` with the single-quote symbols just fine, but however when I modify it to: 
`return pgp.as.format("ST_MakePoint(${lon},  ${lat})", obj.location);`

the output becomes: 
`'ST_MakePoint(103.7716803, 1.3104337)'`

which isn't accepted by the database presumably because of the single quotes. Any suggestions?

**EDIT: it's okay now, found out you can drop the single quotes by setting `_rawDBType = true`**

**Comment by vitaly-t** [comment]
Yes, you have found one of the solutions:
- Either define it on the type, by adding `_rawDBType: true`;
- Or pass it in as a raw variable into the query formatting, i.e. using `^` in the end of the variable name.

The result will be the same. Just don't do both ;)

**Comment by vitaly-t** [comment]
I just saw the way you did it, which does work, but the recommended way of doing it is:

``` js
function providesLocation(obj) {
    obj.getLocation = {
        formatDBType: function () {
            return pgp.as.format("ST_MakePoint(${lon}, ${lat})", obj.location);
        },
        _rawDBType: true
    };
}

function providesPolygon(obj) {
    obj.getPolygon = {
        formatDBType: function () {
            var polygon = {
                minX: parseFloat(obj.boundsArray[0]),
                minY: parseFloat(obj.boundsArray[1]),
                maxX: parseFloat(obj.boundsArray[2]),
                maxY: parseFloat(obj.boundsArray[3])
            }
            return pgp.as.format("ST_MakePolygon(ST_GeomFromText('LINESTRING(${minX} ${minY},${maxX} ${minY},${maxX} ${maxY}, ${minX} ${maxY}, ${minX} ${minY})'))", polygon)
        },
        _rawDBType: true
    }
}
```

**Comment by jurvis** [comment]
@vitaly-t haha thanks for spotting that! was lazy just now :stuck_out_tongue:

**Comment by vitaly-t** [comment]
By the way, the shortest implementation for that method:

``` js
function providesPolygon(obj) {
    obj.getPolygon = {
        formatDBType: function () {
            return pgp.as.format("ST_MakePolygon(ST_GeomFromText('LINESTRING($1 $2, $3 $2, $3 $4, $1 $4, $1 $2)'))", obj.boundsArray);
        },
        _rawDBType: true
    }
}
```

just as an idea, not a recommendation ;)

Actually, if `parseFloat` is needed, then it's different :) just wanted to show more tricks with the formatting :)

**Comment by jurvis** [comment]
@vitaly-t they certainly look really convenient! unfortunately because I get returned string values from Google Maps I'd have to cast it with parseFloat() 😕

**Comment by vitaly-t** [comment]
Yep, I thought of it later only, otherwise wouldn't have written it :)

BTW, in this code:

``` js
function providesLocation(obj) {
  obj.getLocation = {
    formatDBType: function() {
      this._rawDBType= true;
      return pgp.as.format("ST_MakePoint(${lon}, ${lat})", obj.location);
    },
    _rawDBType: true
  };
}
```

calling `this._rawDBType= true;` is redundant ;)

**Comment by jurvis** [comment]
@vitaly-t good spotting, thanks! :+1:
